autonotecards/autonotecards/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from processor import views
from accounts import views as accounts_views


urlpatterns = [
    # url(regex, view function, kwargs (not often used).., (url)name )
    url(r'^$', views.home, name='home'),
    url(r'^signup/$', accounts_views.signup, name='signup'),
    url(r'^pdf/(?P<pk>\d+)/new/$', views.new_pdf, name='new_pdf'),
    # url(r'^about/$', views.about, name='about'), # an about view.
    path('admin/', admin.site.urls),
]

autonotecards/accounts/models.py
from django.db import models

# Create your models here.

autonotecards/processor/models.py
from django.db import models
from django.contrib.auth.models import User


class PdfPack(models.Model):
    """django model--represents a database. PdfPack.ID is auto init'd"""
    desc = models.CharField(max_length=255, blank=True)
    pdfFile = models.FileField(upload_to='documents/')
    uploadTime = models.DateTimeField(auto_now_add=True)
    createdBy = models.ForeignKey(User, on_delete=models.CASCADE)
    divs = models.CharField(max_length=4000, blank=True)
    # note; upload time will upload to $media_root/documents/YYYY/MM/DD

autonotecards/accounts/views.py
from django.shortcuts import render


def signup(request):
    return render(request, 'signup.html')

autonotecards/processor/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import PdfPack
from django.core.files.storage import FileSystemStorage
from django import forms
from .forms import NewPdfForm



def home(request):
    pack = PdfPack.objects.all()
    return render(request, 'home.html', {'PdfPacks': pack})


def new_pdf(request, pk):
    pack = get_object_or_404(PdfPack, pk=pk)
    # get a gemeroc user for now:
    user = User.objects.first()
    if request.method == 'POST':
        form = NewPdfForm(request.POST)
        if form.is_valid():
            pdfFile = form.save(commit=False)
        


    return render(request, 'new_pdf.html')

autonotecards/templates/base.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}NoteCards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}"> # manual css overrides..
    <link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">NoteCards</a>
        </div>
    </nav>
    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %} {% endblock %}
        </ol>
        {% block content %} {% endblock %}
    </div>
</body>

</html>

autonotecards/templates/home.html
{% extends 'base.html' %}
<!DOCTYPE html> {% load static %}
<!--remember to use when we refer to css, js, images-->


{% block breadcrumb %}
<li class="breadcrumb-item active">Upload</li>
{% endblock %} {% block content %}
<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>File</th>
            <th>Upload Time</th>
            <th>Creator</th>
        </tr>
    </thead>
    <tbody>
        <a>Your Uploads:</a> {% for PdfPack in PdfPacks %}
        <tr>
            <td>
                <a href="#">{{ PdfPack.desc }}</a>
            </td>
            <td class="align-middle">{{ PdfPack.uploadTime }}</td>
            <td class="align-middle">{{ PdfPack.created_by }}</td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

autonotecards/templates/new_pdf.html
{% extends 'base.html' %} {% block title %}Upload a New PDF{% endblock %} {% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">PDFs</a></li>
<li class="breadcrumb-item active">New PDF</li>
{% endblock %} {% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <input type="file" name="pdfFile">
    <div class="form-group">
        <label for="id_desc">Description:</label>
        <input type="text" class="form-control" id="id_desc" name="desc">
    </div>
    <div class="form-group">
        <label for="id_divs">Divisions:</label>
        <input type="text" class="form-control" id="id_divs" name="divs">
    </div>
    {% if uploadedFileUrl %}
    <p>File uploaded at: <a href="{{ uploadedFileUrl }}">{{ uploadedFileUrl }}</a></p>
    <p>Your PDF is being processed.</p>
    {% endif %}

    <button type="submit">Upload</button>
</form>
{% endblock %}

autonotecards/templates/signup.html
{% extends 'base.html' %} {% block content %}
<h2>Sign up</h2>
{% endblock %}